# Generated by Django 6.0.2 on 2026-04-06 06:31

import apps.inventory.models.product
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='محذوف؟')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('name', models.CharField(max_length=255, verbose_name='اسم المنتج')),
                ('sku', models.CharField(blank=True, max_length=100, verbose_name='كود المنتج')),
                ('barcode', models.CharField(blank=True, max_length=100, null=True, verbose_name='باركود')),
                ('product_type', models.CharField(choices=[('storable', 'منتج مخزني'), ('service', 'خدمة'), ('consumable', 'مستهلك')], default='storable', max_length=20, verbose_name='نوع المنتج')),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.inventory.models.product.product_image_path, verbose_name='صورة المنتج')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف تفصيلي')),
                ('cost_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='سعر التكلفة الافتراضي')),
                ('average_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='متوسط التكلفة')),
                ('sale_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='سعر البيع الافتراضي')),
                ('reorder_point', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='حد الطلب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'منتج',
                'verbose_name_plural': 'المنتجات',
                'ordering': ['company', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StockBalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل')),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='الكمية الفعلية')),
                ('reserved_quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='الكمية المحجوزة')),
                ('location', models.CharField(blank=True, max_length=50, null=True, verbose_name='موقع التخزين (رف/ممر)')),
                ('reorder_point', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='حد الطلب')),
            ],
            options={
                'verbose_name': 'رصيد مخزون',
                'verbose_name_plural': 'أرصدة المخزون',
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='الكمية')),
                ('unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='تكلفة الوحدة')),
                ('note', models.CharField(blank=True, max_length=255, null=True, verbose_name='ملاحظة')),
            ],
            options={
                'verbose_name': 'سطر حركة مخزنية',
                'verbose_name_plural': 'سطور الحركات المخزنية',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل')),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='رقم المستند')),
                ('transaction_type', models.CharField(choices=[('IN', 'إذن إضافة (وارد)'), ('OUT', 'إذن صرف (صادر)'), ('TRANSFER', 'إذن تحويل داخلي')], max_length=10, verbose_name='نوع الحركة')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ الحركة')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('posted', 'مرحل'), ('cancelled', 'ملغي')], default='draft', max_length=20, verbose_name='الحالة')),
                ('reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم المرجع')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
            ],
            options={
                'verbose_name': 'حركة مخزنية',
                'verbose_name_plural': 'الحركات المخزنية',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='محذوف؟')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('name', models.CharField(max_length=50, verbose_name='اسم الوحدة')),
                ('short_name', models.CharField(max_length=10, verbose_name='الرمز')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشطة')),
            ],
            options={
                'verbose_name': 'وحدة قياس',
                'verbose_name_plural': 'وحدات القياس',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='محذوف؟')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('name', models.CharField(max_length=100, verbose_name='اسم المخزن')),
                ('code', models.CharField(blank=True, max_length=20, verbose_name='كود المخزن')),
                ('warehouse_type', models.CharField(choices=[('main', 'مخزن رئيسي (Main)'), ('sub', 'مخزن فرعي / معرض (Showroom)')], default='sub', max_length=20, verbose_name='نوع المخزن')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='العنوان التفصيلي')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'مخزن',
                'verbose_name_plural': 'المخازن',
                'ordering': ['company', 'branch', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='محذوف؟')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('name', models.CharField(max_length=100, verbose_name='اسم التصنيف')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشطة')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='أيقونة')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='core.company', verbose_name='الشركة')),
            ],
            options={
                'verbose_name': 'تصنيف منتج',
                'verbose_name_plural': 'تصنيفات المنتجات',
                'ordering': ['company', 'parent__name', 'name'],
            },
        ),
    ]
