# Generated by Django 6.0.2 on 2026-02-22 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='code',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='كود المخزن'),
        ),
    ]
