# Generated by Django 6.0.2 on 2026-04-06 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0003_initial'),
        ('core', '0001_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة'),
        ),
        migrations.AddField(
            model_name='category',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='حُذف بواسطة'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='inventory.category', verbose_name='التصنيف الأب'),
        ),
        migrations.AddField(
            model_name='category',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='عُدل بواسطة'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='inventory.category', verbose_name='التصنيف'),
        ),
        migrations.AddField(
            model_name='product',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.company', verbose_name='الشركة'),
        ),
        migrations.AddField(
            model_name='product',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة'),
        ),
        migrations.AddField(
            model_name='product',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='حُذف بواسطة'),
        ),
        migrations.AddField(
            model_name='product',
            name='expense_account',
            field=models.ForeignKey(blank=True, help_text='إذا تُرِك فارغاً، سيتم استخدام حساب التكلفة الخاص بتصنيف المنتج.', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='expense_products', to='accounting.account', verbose_name='حساب المصروفات / التكلفة'),
        ),
        migrations.AddField(
            model_name='product',
            name='income_account',
            field=models.ForeignKey(blank=True, help_text='إذا تُرِك فارغاً، سيتم استخدام حساب الإيرادات الخاص بتصنيف المنتج.', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='income_products', to='accounting.account', verbose_name='حساب الإيرادات'),
        ),
        migrations.AddField(
            model_name='product',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='عُدل بواسطة'),
        ),
        migrations.AddField(
            model_name='stockbalance',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_balances', to='core.company', verbose_name='الشركة'),
        ),
        migrations.AddField(
            model_name='stockbalance',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة'),
        ),
        migrations.AddField(
            model_name='stockbalance',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_balances', to='inventory.product', verbose_name='المنتج'),
        ),
        migrations.AddField(
            model_name='stockbalance',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='عُدل بواسطة'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.product', verbose_name='المنتج'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='عُدل بواسطة'),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_transactions', to='core.company', verbose_name='الشركة'),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة'),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='journal_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_transaction', to='accounting.journalentry', verbose_name='قيد اليومية المرتبط'),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='عُدل بواسطة'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.stocktransaction', verbose_name='الحركة المخزنية'),
        ),
        migrations.AddField(
            model_name='unit',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة'),
        ),
        migrations.AddField(
            model_name='unit',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='حُذف بواسطة'),
        ),
        migrations.AddField(
            model_name='unit',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='عُدل بواسطة'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='inventory.unit', verbose_name='وحدة القياس'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='core.branch', verbose_name='الفرع التابع له'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='core.company', verbose_name='الشركة'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='حُذف بواسطة'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='keeper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_warehouses', to=settings.AUTH_USER_MODEL, verbose_name='أمين المخزن'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='عُدل بواسطة'),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='destination_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transactions', to='inventory.warehouse', verbose_name='المخزن الوجهة'),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='source_warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transactions', to='inventory.warehouse', verbose_name='المخزن المصدر'),
        ),
        migrations.AddField(
            model_name='stockbalance',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_balances', to='inventory.warehouse', verbose_name='المخزن'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('company', 'name', 'parent'), name='unique_category_name_per_parent_per_company'),
        ),
        migrations.AddConstraint(
            model_name='unit',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('name',), name='unique_active_unit_name'),
        ),
        migrations.AddConstraint(
            model_name='unit',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('short_name',), name='unique_active_unit_short_name'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('company', 'sku'), name='unique_active_sku_per_company'),
        ),
        migrations.AddConstraint(
            model_name='warehouse',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('branch', 'name'), name='unique_active_warehouse_name_per_branch'),
        ),
        migrations.AddConstraint(
            model_name='warehouse',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('company', 'code'), name='unique_active_warehouse_code_per_company'),
        ),
        migrations.AddConstraint(
            model_name='stocktransaction',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='unique_stock_transaction_code_per_company'),
        ),
        migrations.AddConstraint(
            model_name='stockbalance',
            constraint=models.UniqueConstraint(fields=('company', 'product', 'warehouse'), name='unique_product_per_warehouse_per_company'),
        ),
    ]
