# Generated by Django 6.0.2 on 2026-03-25 03:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdocument',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ الإذن'),
        ),
    ]
