# Generated by Django 6.0.2 on 2026-02-19 13:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_stock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل')),
                ('movement_type', models.CharField(choices=[('IN', 'وارد (إضافة)'), ('OUT', 'صادر (صرف)')], max_length=3, verbose_name='نوع الحركة')),
                ('quantity', models.PositiveIntegerField(verbose_name='الكمية')),
                ('reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم الفاتورة/المرجع')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='بواسطة')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.product', verbose_name='المنتج')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='عُدل بواسطة')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.warehouse', verbose_name='المخزن')),
            ],
            options={
                'verbose_name': 'حركة مخزنية',
                'verbose_name_plural': 'حركات المخازن',
                'ordering': ['-created_at'],
            },
        ),
    ]
