# Generated by Django 6.0.2 on 2026-02-24 18:19

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='محذوف؟')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الكمية')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر الوحدة')),
                ('total_cost', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='التكلفة الإجمالية')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
            ],
            options={
                'verbose_name': 'منتج أمر الشراء',
                'verbose_name_plural': 'منتجات أمر الشراء',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='محذوف؟')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('po_number', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='رقم أمر الشراء')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('sent', 'تم الإرسال'), ('approved', 'موافق عليه'), ('cancelled', 'ملغي'), ('converted', 'تحول لفاتورة')], default='draft', max_length=20, verbose_name='الحالة')),
                ('order_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ الطلب')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='تاريخ التوريد المتوقع')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=12, verbose_name='إجمالي أمر الشراء')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='core.branch', verbose_name='الفرع')),
            ],
            options={
                'verbose_name': 'أمر شراء',
                'verbose_name_plural': 'أوامر الشراء',
                'ordering': ['-order_date', '-id'],
            },
        ),
    ]
