# Generated by Django 6.0.2 on 2026-03-25 03:12

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseInvoiceItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='محذوف؟')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الكمية')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر الوحدة')),
                ('total_cost', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='التكلفة الإجمالية')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
            ],
            options={
                'verbose_name': 'عنصر فاتورة المشتريات',
                'verbose_name_plural': 'عناصر فاتورة المشتريات',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='محذوف؟')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('po_number', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='رقم أمر الشراء')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('sent', 'تم الإرسال'), ('approved', 'موافق عليه'), ('cancelled', 'ملغي'), ('converted', 'تحول لفاتورة')], default='draft', max_length=20, verbose_name='الحالة')),
                ('order_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ الطلب')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='تاريخ التوريد المتوقع')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=12, verbose_name='إجمالي أمر الشراء')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
            ],
            options={
                'verbose_name': 'أمر شراء',
                'verbose_name_plural': 'أوامر الشراء',
                'ordering': ['-order_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='محذوف؟')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الكمية')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر الوحدة')),
                ('total_cost', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='التكلفة الإجمالية')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
            ],
            options={
                'verbose_name': 'منتج أمر الشراء',
                'verbose_name_plural': 'منتجات أمر الشراء',
            },
        ),
        migrations.CreateModel(
            name='PurchaseInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='محذوف؟')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('invoice_number', models.CharField(blank=True, max_length=50, unique=True, verbose_name='رقم الفاتورة')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('received', 'تم الاستلام (تؤثر على المخزن)'), ('paid', 'مدفوعة'), ('cancelled', 'ملغاة')], default='draft', max_length=20, verbose_name='الحالة')),
                ('invoice_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ الفاتورة')),
                ('vendor_bill_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم فاتورة المورد')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=12, verbose_name='إجمالي الفاتورة')),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='تكلفة الشحن الداخلي')),
                ('clearance_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='تكلفة الأرضيات والتخليص')),
                ('commission_percentage', models.DecimalField(decimal_places=2, default=5.0, max_digits=5, verbose_name='نسبة عمولة المورد (%)')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='purchase_invoices', to='core.branch', verbose_name='الفرع')),
            ],
            options={
                'verbose_name': 'فاتورة مشتريات',
                'verbose_name_plural': 'فواتير المشتريات',
                'ordering': ['-invoice_date', '-id'],
            },
        ),
    ]
