# Generated by Django 6.0.2 on 2026-04-06 09:46

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseInvoiceItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الكمية')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر الوحدة')),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12, verbose_name='إجمالي السطر')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
            ],
            options={
                'verbose_name': 'عنصر فاتورة مشتريات',
                'verbose_name_plural': 'عناصر فواتير المشتريات',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='محذوف؟')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('invoice_number', models.CharField(blank=True, max_length=50, verbose_name='رقم الفاتورة')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('posted', 'مرحلة'), ('cancelled', 'ملغاة')], default='draft', max_length=20, verbose_name='الحالة')),
                ('invoice_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ الفاتورة')),
                ('vendor_bill_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم فاتورة المورد')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12, verbose_name='إجمالي الفاتورة')),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='تكلفة الشحن الداخلي')),
                ('clearance_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='تكلفة الأرضيات والتخليص')),
                ('commission_percentage', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=5, verbose_name='نسبة عمولة المورد (%)')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='purchase_invoices', to='core.branch', verbose_name='الفرع')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='purchase_invoices', to='core.company', verbose_name='الشركة')),
            ],
            options={
                'verbose_name': 'فاتورة مشتريات',
                'verbose_name_plural': 'فواتير المشتريات',
                'ordering': ['-invoice_date', '-id'],
            },
        ),
    ]
