# Generated by Django 6.0.2 on 2026-05-16 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_fix_cash_bank_reconciliation_flags'),
        ('purchases', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoice',
            name='journal_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_invoice', to='accounting.journalentry'),
        ),
    ]
