# Generated by Django 6.0.2 on 2026-03-11 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0003_purchaseinvoice_purchaseinvoiceitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoice',
            name='clearance_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='تكلفة الأرضيات والتخليص'),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='commission_percentage',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5, verbose_name='نسبة عمولة المورد (%)'),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='تكلفة الشحن الداخلي'),
        ),
    ]
