# Generated by Django 6.0.2 on 2026-04-06 09:46

import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='محذوف؟')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('code', models.CharField(help_text='كود فريد داخل نفس الشركة (مثال: 1120).', max_length=50, verbose_name='كود الحساب')),
                ('name', models.CharField(max_length=255, verbose_name='اسم الحساب')),
                ('account_type', models.CharField(choices=[('asset', 'أصل (Asset)'), ('liability', 'دين / التزام (Liability)'), ('equity', 'حقوق ملكية (Equity)'), ('income', 'إيراد (Income/Revenue)'), ('expense', 'مصروف (Expense)')], max_length=20, verbose_name='نوع الحساب')),
                ('normal_balance', models.CharField(choices=[('debit', 'مدين (Debit)'), ('credit', 'دائن (Credit)')], help_text='مدين للأصول والمصروفات، ودائن للخصوم وحقوق الملكية والإيرادات.', max_length=10, verbose_name='طبيعة الحساب')),
                ('is_postable', models.BooleanField(default=True, help_text='إذا كان False فهو حساب تجميعي فقط ولا تُرحّل عليه قيود مباشرة.', verbose_name='قابل للترحيل')),
                ('allow_reconciliation', models.BooleanField(default=False, help_text='يفعل عادةً لحسابات العملاء والموردين والبنوك.', verbose_name='يقبل التسوية')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'حساب',
                'verbose_name_plural': 'دليل الحسابات',
                'ordering': ['company', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='محذوف؟')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الدفتر')),
                ('code', models.CharField(help_text='مثل: SAL, PUR, CASH, BNK', max_length=10, verbose_name='الكود')),
                ('type', models.CharField(choices=[('sale', 'مبيعات (Sales)'), ('purchase', 'مشتريات (Purchases)'), ('cash', 'نقدية (Cash)'), ('bank', 'بنك (Bank)'), ('general', 'عمليات متنوعة (General/Miscellaneous)')], max_length=20, verbose_name='النوع')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'دفتر يومية',
                'verbose_name_plural': 'دفاتر اليومية',
                'ordering': ['company', 'type', 'code'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='محذوف؟')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('entry_number', models.CharField(blank=True, help_text='يتم توليده تلقائياً بناءً على كود الدفتر.', max_length=50, verbose_name='رقم القيد')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ القيد')),
                ('reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم المرجع')),
                ('status', models.CharField(choices=[('draft', 'مسودة (Draft)'), ('posted', 'مُرحّل (Posted)'), ('cancelled', 'ملغي (Cancelled)')], default='draft', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, verbose_name='البيان / الملاحظات')),
            ],
            options={
                'verbose_name': 'قيد يومية',
                'verbose_name_plural': 'قيود اليومية',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='JournalItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل')),
                ('description', models.CharField(max_length=255, verbose_name='البيان')),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='مدين')),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='دائن')),
            ],
            options={
                'verbose_name': 'سطر القيد',
                'verbose_name_plural': 'سطور القيود',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='محذوف؟')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('voucher_number', models.CharField(blank=True, max_length=50, verbose_name='رقم السند')),
                ('payment_type', models.CharField(choices=[('inbound', 'سند قبض (من عميل)'), ('outbound', 'سند صرف (لمورد)')], max_length=20, verbose_name='نوع السند')),
                ('payment_method', models.CharField(choices=[('cash', 'نقدي (خزينة)'), ('bank', 'تحويل بنكي / شيك')], max_length=20, verbose_name='طريقة الدفع')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='المبلغ')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ السند')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('posted', 'مرحّل'), ('cancelled', 'ملغي')], default='draft', max_length=20, verbose_name='الحالة')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='المرجع / رقم الشيك')),
                ('notes', models.TextField(blank=True, verbose_name='البيان / الملاحظات')),
            ],
            options={
                'verbose_name': 'سند قبض / صرف',
                'verbose_name_plural': 'سندات القبض والصرف',
                'ordering': ['-date', '-id'],
            },
        ),
    ]
