# Generated by Django 6.0.2 on 2026-04-06 06:31

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='محذوف؟')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('code', models.CharField(help_text='كود فريد يحدد موقع الحساب في الدليل (مثال: 1120).', max_length=50, unique=True, verbose_name='كود الحساب')),
                ('name', models.CharField(max_length=255, verbose_name='اسم الحساب')),
                ('account_type', models.CharField(choices=[('asset', 'أصل (Asset)'), ('liability', 'دين / التزام (Liability)'), ('equity', 'حقوق ملكية (Equity)'), ('income', 'إيراد (Income/Revenue)'), ('expense', 'مصروف (Expense)')], max_length=20, verbose_name='نوع الحساب')),
                ('normal_balance', models.CharField(choices=[('debit', 'مدين (Debit)'), ('credit', 'دائن (Credit)')], default='debit', help_text='يحدد إذا كان الحساب بطبيعته مديناً (كالأصول) أو دائناً (كالخصوم).', max_length=10, verbose_name='طبيعة الحساب')),
                ('is_leaf', models.BooleanField(default=True, help_text='إذا كان مفعّلاً، يمكن رمي قيود يومية عليه مباشرةً. إذا كان معطّلاً، فهو حساب تجميعي (أب) يجمع أرصدة أولاده فقط.', verbose_name='قابل للترحيل (حساب فرعي)')),
                ('allow_reconciliation', models.BooleanField(default=False, help_text='يُفعل لحسابات العملاء والموردين والبنوك لربط الفواتير بالمدفوعات (مطابقة الأرصدة).', verbose_name='يقبل التسوية (Reconciliation)')),
                ('is_active', models.BooleanField(default=True, help_text='تعطيل الحساب يمنع استخدامه في المعاملات الجديدة دون حذفه من النظام.', verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'حساب',
                'verbose_name_plural': 'دليل الحسابات',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='محذوف؟')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الدفتر')),
                ('code', models.CharField(help_text='كود مختصر للدفتر، مثلاً: INV للمبيعات، BNK للبنك.', max_length=10, unique=True, verbose_name='الكود')),
                ('type', models.CharField(choices=[('sale', 'مبيعات (Sales)'), ('purchase', 'مشتريات (Purchases)'), ('cash', 'نقدية (Cash)'), ('bank', 'بنك (Bank)'), ('general', 'عمليات متنوعة (General/Miscellaneous)')], max_length=20, verbose_name='النوع')),
            ],
            options={
                'verbose_name': 'دفتر يومية',
                'verbose_name_plural': 'دفاتر اليومية',
                'ordering': ['type', 'code'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='محذوف؟')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('entry_number', models.CharField(blank=True, help_text='يتم توليده تلقائياً عند الحفظ بناءً على كود الدفتر.', max_length=50, unique=True, verbose_name='رقم القيد')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ القيد')),
                ('reference', models.CharField(blank=True, help_text='يُستخدم لربط القيد بالمستند الأصلي (مثال: INV-2026-001).', max_length=100, null=True, verbose_name='رقم المرجع (رقم الفاتورة/السند)')),
                ('status', models.CharField(choices=[('draft', 'مسودة (Draft)'), ('posted', 'مُرحّل (Posted)'), ('cancelled', 'ملغي (Cancelled)')], default='draft', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, verbose_name='البيان / الملاحظات')),
            ],
            options={
                'verbose_name': 'قيد يومية',
                'verbose_name_plural': 'قيود اليومية',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='JournalItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='محذوف؟')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('description', models.CharField(max_length=255, verbose_name='البيان')),
                ('debit', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='مدين (Debit)')),
                ('credit', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='دائن (Credit)')),
            ],
            options={
                'verbose_name': 'سطر القيد',
                'verbose_name_plural': 'سطور القيد',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='محذوف؟')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('name', models.CharField(blank=True, max_length=50, unique=True, verbose_name='رقم السند')),
                ('payment_type', models.CharField(choices=[('inbound', 'سند قبض (من عميل)'), ('outbound', 'سند صرف (لمورد)')], max_length=20, verbose_name='نوع السند')),
                ('payment_method', models.CharField(choices=[('cash', 'نقدي (خزينة)'), ('bank', 'تحويل بنكي / شيك')], max_length=20, verbose_name='طريقة الدفع')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ السند')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='المرجع / رقم الشيك')),
                ('notes', models.TextField(blank=True, verbose_name='البيان / الملاحظات')),
            ],
            options={
                'verbose_name': 'سند دفع / قبض',
                'verbose_name_plural': 'سندات الدفع والقبض',
                'ordering': ['-date', '-id'],
            },
        ),
    ]
