# Generated by Django 6.0.2 on 2026-03-01 20:15

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        ('partners', '0003_remove_partner_balance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='محذوف؟')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('name', models.CharField(blank=True, max_length=50, unique=True, verbose_name='رقم السند')),
                ('payment_type', models.CharField(choices=[('inbound', 'سند قبض (من عميل)'), ('outbound', 'سند صرف (لمورد)')], max_length=20, verbose_name='نوع السند')),
                ('payment_method', models.CharField(choices=[('cash', 'نقدي (خزينة)'), ('bank', 'تحويل بنكي / شيك')], max_length=20, verbose_name='طريقة الدفع')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ السند')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='المرجع / رقم الشيك')),
                ('notes', models.TextField(blank=True, verbose_name='البيان / الملاحظات')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='حُذف بواسطة')),
                ('journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='linked_payment', to='accounting.journalentry', verbose_name='قيد اليومية المرتبط')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='payments', to='partners.partner', verbose_name='الشريك (المورد/العميل)')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='عُدل بواسطة')),
            ],
            options={
                'verbose_name': 'سند دفع / قبض',
                'verbose_name_plural': 'سندات الدفع والقبض',
                'ordering': ['-date', '-id'],
            },
        ),
    ]
