# Generated by Django 6.0.2 on 2026-04-06 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0002_initial'),
        ('core', '0001_initial'),
        ('partners', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة'),
        ),
        migrations.AddField(
            model_name='account',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='حُذف بواسطة'),
        ),
        migrations.AddField(
            model_name='account',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='children', to='accounting.account', verbose_name='الحساب الأب'),
        ),
        migrations.AddField(
            model_name='account',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='عُدل بواسطة'),
        ),
        migrations.AddField(
            model_name='journal',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journals', to='core.company', verbose_name='الشركة'),
        ),
        migrations.AddField(
            model_name='journal',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة'),
        ),
        migrations.AddField(
            model_name='journal',
            name='default_account',
            field=models.ForeignKey(blank=True, help_text='يُستخدم تلقائياً عند إنشاء قيود من هذا الدفتر. يجب أن يكون حساباً قابلاً للترحيل ومتوافقاً مع نوع الدفتر.', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='default_journals', to='accounting.account', verbose_name='الحساب الافتراضي'),
        ),
        migrations.AddField(
            model_name='journal',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='حُذف بواسطة'),
        ),
        migrations.AddField(
            model_name='journal',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='عُدل بواسطة'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='core.company', verbose_name='الشركة'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='حُذف بواسطة'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='entries', to='accounting.journal', verbose_name='دفتر اليومية'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='عُدل بواسطة'),
        ),
        migrations.AddField(
            model_name='journalitem',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='journal_items', to='accounting.account', verbose_name='الحساب'),
        ),
        migrations.AddField(
            model_name='journalitem',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة'),
        ),
        migrations.AddField(
            model_name='journalitem',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounting.journalentry', verbose_name='قيد اليومية'),
        ),
        migrations.AddField(
            model_name='journalitem',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_items', to='partners.partner', verbose_name='الشريك (عميل / مورد)'),
        ),
        migrations.AddField(
            model_name='journalitem',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='عُدل بواسطة'),
        ),
        migrations.AddField(
            model_name='payment',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='payments', to='accounting.account', verbose_name='حساب الخزينة / البنك'),
        ),
        migrations.AddField(
            model_name='payment',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='payments', to='core.branch', verbose_name='الفرع'),
        ),
        migrations.AddField(
            model_name='payment',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='payments', to='core.company', verbose_name='الشركة'),
        ),
        migrations.AddField(
            model_name='payment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة'),
        ),
        migrations.AddField(
            model_name='payment',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='حُذف بواسطة'),
        ),
        migrations.AddField(
            model_name='payment',
            name='journal_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_payment', to='accounting.journalentry', verbose_name='قيد اليومية المرتبط'),
        ),
        migrations.AddField(
            model_name='payment',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='payments', to='partners.partner', verbose_name='الشريك (المورد/العميل)'),
        ),
        migrations.AddField(
            model_name='payment',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='عُدل بواسطة'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['company', 'code'], name='accounting__company_4777d3_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['company', 'parent'], name='accounting__company_b8cecb_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['company', 'account_type'], name='accounting__company_2e81bf_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['company', 'is_active'], name='accounting__company_e85481_idx'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('company', 'code'), name='unique_account_code_per_company'),
        ),
        migrations.AddIndex(
            model_name='journal',
            index=models.Index(fields=['company', 'code'], name='accounting__company_06f68c_idx'),
        ),
        migrations.AddIndex(
            model_name='journal',
            index=models.Index(fields=['company', 'type'], name='accounting__company_d04129_idx'),
        ),
        migrations.AddIndex(
            model_name='journal',
            index=models.Index(fields=['company', 'is_active'], name='accounting__company_52ae67_idx'),
        ),
        migrations.AddConstraint(
            model_name='journal',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('company', 'code'), name='unique_journal_code_per_company'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['company', 'date'], name='accounting__company_7e9397_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['company', 'status'], name='accounting__company_7eceea_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['company', 'reference'], name='accounting__company_246138_idx'),
        ),
        migrations.AddConstraint(
            model_name='journalentry',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('company', 'entry_number'), name='unique_journal_entry_number_per_company'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['company', 'date'], name='accounting__company_82b2b6_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['company', 'payment_type'], name='accounting__company_30806f_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['company', 'status'], name='accounting__company_a0e3a4_idx'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('branch', 'voucher_number'), name='unique_payment_voucher_number_per_branch'),
        ),
    ]
