# Generated by Django 6.0.2 on 2026-03-18 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_payment'),
        ('partners', '0003_remove_partner_balance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['code'], 'verbose_name': 'حساب', 'verbose_name_plural': 'دليل الحسابات'},
        ),
        migrations.AlterModelOptions(
            name='journal',
            options={'ordering': ['type', 'code'], 'verbose_name': 'دفتر يومية', 'verbose_name_plural': 'دفاتر اليومية'},
        ),
        migrations.AddField(
            model_name='account',
            name='is_leaf',
            field=models.BooleanField(default=True, help_text='إذا كان مفعّلاً، يمكن رمي قيود يومية عليه مباشرةً. إذا كان معطّلاً، فهو حساب تجميعي (أب) يجمع أرصدة أولاده فقط.', verbose_name='قابل للترحيل (حساب فرعي)'),
        ),
        migrations.AddField(
            model_name='account',
            name='normal_balance',
            field=models.CharField(choices=[('debit', 'مدين (Debit)'), ('credit', 'دائن (Credit)')], default='debit', help_text='يحدد إذا كان الحساب بطبيعته مديناً (كالأصول) أو دائناً (كالخصوم).', max_length=10, verbose_name='طبيعة الحساب'),
        ),
        migrations.AlterField(
            model_name='account',
            name='allow_reconciliation',
            field=models.BooleanField(default=False, help_text='يُفعل لحسابات العملاء والموردين والبنوك لربط الفواتير بالمدفوعات (مطابقة الأرصدة).', verbose_name='يقبل التسوية (Reconciliation)'),
        ),
        migrations.AlterField(
            model_name='account',
            name='code',
            field=models.CharField(help_text='كود فريد يحدد موقع الحساب في الدليل (مثال: 1120).', max_length=50, unique=True, verbose_name='كود الحساب'),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_active',
            field=models.BooleanField(default=True, help_text='تعطيل الحساب يمنع استخدامه في المعاملات الجديدة دون حذفه من النظام.', verbose_name='نشط'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='code',
            field=models.CharField(help_text='كود مختصر للدفتر، مثلاً: INV للمبيعات، BNK للبنك.', max_length=10, unique=True, verbose_name='الكود'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='default_account',
            field=models.ForeignKey(blank=True, help_text='يُستخدم هذا الحساب أوتوماتيكياً عند إنشاء قيد من هذا الدفتر. يجب أن يكون حساباً ختامياً (قابلاً للترحيل) ويتوافق مع نوع الدفتر.', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='default_journals', to='accounting.account', verbose_name='الحساب الافتراضي'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='entry_number',
            field=models.CharField(blank=True, help_text='يتم توليده تلقائياً عند الحفظ بناءً على كود الدفتر.', max_length=50, unique=True, verbose_name='رقم القيد'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='reference',
            field=models.CharField(blank=True, help_text='يُستخدم لربط القيد بالمستند الأصلي (مثال: INV-2026-001).', max_length=100, null=True, verbose_name='رقم المرجع (رقم الفاتورة/السند)'),
        ),
        migrations.AlterField(
            model_name='journalitem',
            name='partner',
            field=models.ForeignKey(blank=True, help_text='إلزامي للحسابات التي تقبل التسوية (كالعملاء والموردين).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_items', to='partners.partner', verbose_name='الشريك (مورد / عميل)'),
        ),
    ]
