# Generated by Django 6.0.2 on 2026-05-07 17:27

import apps.ai_assistant.models.document
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='محذوف؟')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('file', models.FileField(upload_to=apps.ai_assistant.models.document.document_upload_path, verbose_name='File')),
                ('original_filename', models.CharField(blank=True, max_length=255, verbose_name='Original filename')),
                ('file_type', models.CharField(blank=True, max_length=10, verbose_name='File type')),
                ('file_size', models.PositiveBigIntegerField(default=0, verbose_name='File size')),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('failed', 'Failed')], default='uploaded', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_documents', to='core.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='حُذف بواسطة')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='عُدل بواسطة')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_uploaded_documents', to=settings.AUTH_USER_MODEL, verbose_name='Uploaded by')),
            ],
            options={
                'verbose_name': 'AI Document',
                'verbose_name_plural': 'AI Documents',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'status'], name='ai_assistan_company_3efd8d_idx'), models.Index(fields=['uploaded_by'], name='ai_assistan_uploade_f6879f_idx')],
            },
        ),
    ]
