# Generated by Django 6.0.2 on 2026-05-07 17:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0001_initial'),
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='uploaded', max_length=20, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chunk_index', models.PositiveIntegerField(verbose_name='Chunk index')),
                ('text', models.TextField(verbose_name='Text')),
                ('page_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Page number')),
                ('char_start', models.PositiveIntegerField(default=0, verbose_name='Character start')),
                ('char_end', models.PositiveIntegerField(default=0, verbose_name='Character end')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_document_chunks', to='core.company', verbose_name='Company')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='ai_assistant.document', verbose_name='Document')),
            ],
            options={
                'verbose_name': 'AI Document Chunk',
                'verbose_name_plural': 'AI Document Chunks',
                'ordering': ['document', 'chunk_index'],
                'indexes': [models.Index(fields=['company', 'document'], name='ai_assistan_company_c65c27_idx'), models.Index(fields=['document', 'chunk_index'], name='ai_assistan_documen_863277_idx')],
                'constraints': [models.UniqueConstraint(fields=('document', 'chunk_index'), name='unique_ai_document_chunk_index')],
            },
        ),
    ]
