# Generated by Django 6.0.2 on 2026-05-07 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0002_alter_document_status_documentchunk'),
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentchunk',
            name='embedding',
            field=models.JSONField(blank=True, null=True, verbose_name='Embedding'),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='embedding_model',
            field=models.CharField(blank=True, max_length=100, verbose_name='Embedding model'),
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=models.Index(fields=['embedding_model'], name='ai_assistan_embeddi_6fba21_idx'),
        ),
    ]
