# Generated by Django 6.0.2 on 2026-03-25 03:12

import apps.core.models.attachments
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'إضافة'), ('update', 'تعديل'), ('delete', 'حذف'), ('restore', 'استرجاع')], max_length=15, verbose_name='نوع العملية')),
                ('object_id', models.CharField(max_length=50)),
                ('changes', models.JSONField(blank=True, null=True, verbose_name='التغييرات')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='وقت العملية')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('browser_info', models.TextField(blank=True, null=True, verbose_name='معلومات المتصفح')),
            ],
            options={
                'verbose_name': 'سجل تتبع',
                'verbose_name_plural': 'سجلات التتبع',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='محذوف؟')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('name', models.CharField(max_length=255, verbose_name='اسم الفرع')),
                ('code', models.CharField(blank=True, help_text='يترك فارغاً للتوليد التلقائي (مثال: BR-001)', max_length=50, verbose_name='كود الفرع')),
                ('address', models.TextField(blank=True, null=True, verbose_name='عنوان الفرع')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='هاتف الفرع')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'فرع',
                'verbose_name_plural': 'الفروع',
                'ordering': ['company', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='محذوف؟')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('name', models.CharField(max_length=255, verbose_name='اسم الشركة')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='companies/logos/', verbose_name='شعار الشركة')),
                ('tax_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='الرقم الضريبي')),
                ('commercial_record', models.CharField(blank=True, max_length=50, null=True, verbose_name='السجل التجاري')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم الهاتف الرئيسي')),
                ('website', models.URLField(blank=True, null=True, verbose_name='الموقع الإلكتروني')),
                ('address', models.TextField(blank=True, null=True, verbose_name='العنوان الرئيسي')),
            ],
            options={
                'verbose_name': 'الشركة',
                'verbose_name_plural': 'الشركات',
            },
        ),
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='مفتاح فريد لتمييز نوع المستند، مثل: invoice_branch1_2026', max_length=100, unique=True, verbose_name='كود التسلسل')),
                ('prefix', models.CharField(blank=True, default='', help_text='نص يظهر قبل الرقم، مثل: INV-2026-', max_length=20, verbose_name='البادئة')),
                ('current_value', models.PositiveIntegerField(default=0, verbose_name='القيمة الحالية')),
                ('padding', models.PositiveIntegerField(default=5, help_text='عدد الأصفار، 5 تعني 00001', verbose_name='عدد الخانات')),
            ],
            options={
                'verbose_name': 'عداد تسلسلي',
                'verbose_name_plural': 'عدادات تسلسلية',
            },
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل')),
                ('system_name', models.CharField(default='My ERP', max_length=100, verbose_name='اسم النظام')),
                ('is_maintenance_mode', models.BooleanField(default=False, help_text='إذا تم تفعيله، لن يتمكن الموظفون من الدخول.', verbose_name='وضع الصيانة')),
                ('allow_registration', models.BooleanField(default=False, help_text='هل يسمح للمستخدمين الجدد بإنشاء حسابات بأنفسهم؟', verbose_name='السماح بالتسجيل')),
                ('default_currency', models.CharField(default='EGP', max_length=10, verbose_name='العملة الافتراضية')),
                ('default_vat_percentage', models.DecimalField(decimal_places=2, default=14.0, max_digits=5, verbose_name='نسبة ضريبة القيمة المضافة (%)')),
                ('decimal_places', models.PositiveSmallIntegerField(default=2, help_text='للأرقام المالية (مثلاً 2 لـ 10.50)', verbose_name='عدد الكسور العشرية')),
                ('session_timeout_minutes', models.PositiveIntegerField(default=60, verbose_name='وقت انتهاء الجلسة (دقيقة)')),
            ],
            options={
                'verbose_name': 'إعدادات النظام',
                'verbose_name_plural': 'إعدادات النظام',
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل')),
                ('object_id', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to=apps.core.models.attachments.get_attachment_upload_path, verbose_name='الملف')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='اسم توضيحي')),
                ('note', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('file_type', models.CharField(blank=True, max_length=10, verbose_name='نوع الامتداد')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'مرفق',
                'verbose_name_plural': 'المرفقات',
                'ordering': ['-created_at'],
            },
        ),
    ]
