# Generated by Django 6.0.2 on 2026-02-08 17:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='محذوف؟')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('name', models.CharField(max_length=255, verbose_name='اسم الشركة')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='companies/logos/', verbose_name='شعار الشركة')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني للشركة')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم الهاتف')),
                ('website', models.URLField(blank=True, null=True, verbose_name='الموقع الإلكتروني')),
                ('tax_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='الرقم الضريبي')),
                ('commercial_record', models.CharField(blank=True, max_length=50, null=True, verbose_name='السجل التجاري')),
                ('address', models.TextField(blank=True, null=True, verbose_name='العنوان التفصيلي')),
                ('currency', models.CharField(default='EGP', max_length=10, verbose_name='العملة الافتراضية')),
            ],
            options={
                'verbose_name': 'الشركة',
                'verbose_name_plural': 'الشركات',
            },
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل')),
                ('system_name', models.CharField(default='My ERP', max_length=100, verbose_name='اسم النظام')),
                ('is_maintenance_mode', models.BooleanField(default=False, help_text='إذا تم تفعيله، لن يتمكن الموظفون من الدخول.', verbose_name='وضع الصيانة')),
                ('allow_registration', models.BooleanField(default=False, help_text='هل يسمح للمستخدمين الجدد بإنشاء حسابات بأنفسهم؟', verbose_name='السماح بالتسجيل')),
                ('default_currency', models.CharField(default='EGP', max_length=10, verbose_name='العملة الافتراضية')),
                ('default_vat_percentage', models.DecimalField(decimal_places=2, default=14.0, max_digits=5, verbose_name='نسبة ضريبة القيمة المضافة (%)')),
                ('decimal_places', models.PositiveSmallIntegerField(default=2, help_text='للأرقام المالية (مثلاً 2 لـ 10.50)', verbose_name='عدد الكسور العشرية')),
                ('session_timeout_minutes', models.PositiveIntegerField(default=60, verbose_name='وقت انتهاء الجلسة (دقيقة)')),
            ],
            options={
                'verbose_name': 'إعدادات النظام',
                'verbose_name_plural': 'إعدادات النظام',
            },
        ),
    ]
