# Generated by Django 6.0.2 on 2026-02-24 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='code',
            field=models.CharField(blank=True, help_text='يترك فارغاً للتوليد التلقائي (مثال: BR-001)', max_length=50, verbose_name='كود الفرع'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='core.company', verbose_name='الشركة التابعة'),
        ),
    ]
