# Generated by Django 6.0.2 on 2026-02-09 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_company_currency_alter_company_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='مفتاح فريد لتمييز نوع المستند، مثل: invoice, product_sku', max_length=50, unique=True, verbose_name='كود التسلسل')),
                ('prefix', models.CharField(blank=True, default='', help_text='نص يظهر قبل الرقم، مثل: INV-', max_length=20, verbose_name='البادئة')),
                ('current_value', models.PositiveIntegerField(default=0, verbose_name='القيمة الحالية')),
                ('padding', models.PositiveIntegerField(default=5, help_text='عدد الأصفار، 5 تعني 00001', verbose_name='عدد الخانات')),
            ],
            options={
                'verbose_name': 'عداد تسلسلي',
                'verbose_name_plural': 'عدادات تسلسلية',
            },
        ),
    ]
