# Generated by Django 6.0.2 on 2026-02-09 01:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0005_attachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'إضافة'), ('update', 'تعديل'), ('delete', 'حذف')], max_length=10, verbose_name='نوع العملية')),
                ('object_id', models.CharField(max_length=50)),
                ('changes', models.JSONField(blank=True, null=True, verbose_name='التغييرات')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='وقت العملية')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('browser_info', models.CharField(blank=True, max_length=255, null=True, verbose_name='معلومات المتصفح')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'سجل تتبع',
                'verbose_name_plural': 'سجلات التتبع',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='core_auditl_content_fec0c4_idx'), models.Index(fields=['user'], name='core_auditl_user_id_2ff9b7_idx')],
            },
        ),
    ]
