# Generated by Django 6.0.2 on 2026-02-20 15:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_auditlog_core_auditl_content_fec0c4_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='code',
            field=models.CharField(help_text='مثال: BR-CAI-01', max_length=50, verbose_name='كود الفرع'),
        ),
        migrations.AlterField(
            model_name='sequence',
            name='key',
            field=models.CharField(help_text='مفتاح فريد لتمييز نوع المستند، مثل: invoice_branch1_2026', max_length=100, unique=True, verbose_name='كود التسلسل'),
        ),
        migrations.AlterField(
            model_name='sequence',
            name='prefix',
            field=models.CharField(blank=True, default='', help_text='نص يظهر قبل الرقم، مثل: INV-2026-', max_length=20, verbose_name='البادئة'),
        ),
        migrations.AddConstraint(
            model_name='branch',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('code',), name='unique_active_branch_code'),
        ),
    ]
