from django.db import models
from django.utils.translation import gettext_lazy as _
from django.utils import timezone
from apps.core.models import SoftDeleteModel, Sequence

# ==========================================
# 1. Purchase Invoice Model (Header)
# ==========================================
class PurchaseInvoice(SoftDeleteModel):
    # Statuses for the actual invoice. 'received' means items are in the warehouse.
    STATUS_CHOICES = [
        ('draft', _('مسودة')),
        ('received', _('تم الاستلام (تؤثر على المخزن)')),
        ('paid', _('مدفوعة')),
        ('cancelled', _('ملغاة')),
    ]

    # this is the internal invoice number generated by our ERP system
    invoice_number = models.CharField(
        max_length=50, 
        unique=True, 
        blank=True, 
        verbose_name=_("رقم الفاتورة")
    )
    
    # reference to the original purchase order (nullable, as we might buy directly without a PO)
    purchase_order = models.ForeignKey(
        'purchases.PurchaseOrder', 
        on_delete=models.SET_NULL, 
        null=True, 
        blank=True, 
        related_name='invoices', 
        verbose_name=_("أمر الشراء المرتبط")
    )
    
    branch = models.ForeignKey(
        'core.Branch', 
        on_delete=models.RESTRICT, 
        related_name='purchase_invoices', 
        verbose_name=_("الفرع")
    )

    supplier = models.ForeignKey(
        'partners.Partner', 
        on_delete=models.RESTRICT, 
        limit_choices_to={'partner_type__in': ['supplier', 'both']},
        related_name='purchase_invoices', 
        verbose_name=_("المورد")
    )

    warehouse = models.ForeignKey(
        'inventory.Warehouse',
        on_delete=models.RESTRICT,
        related_name='purchase_invoices',
        verbose_name=_("مخزن الاستلام")
    )

    status = models.CharField(
        max_length=20, 
        choices=STATUS_CHOICES, 
        default='draft', 
        verbose_name=_("الحالة")
    )

    invoice_date = models.DateField(
        default=timezone.now, 
        verbose_name=_("تاريخ الفاتورة")
    )
    
    # The physical invoice number provided by the supplier (crucial for accounting matching)
    vendor_bill_number = models.CharField(
        max_length=100, 
        blank=True, 
        null=True, 
        verbose_name=_("رقم فاتورة المورد")
    )

    total_amount = models.DecimalField(
        max_digits=12, 
        decimal_places=2, 
        default=0.00, 
        verbose_name=_("إجمالي الفاتورة"),
        editable=False
    )
    
    # حقول التكلفة الشاملة (Landed Costs)
    shipping_cost = models.DecimalField(_("تكلفة الشحن الداخلي"), max_digits=10, decimal_places=2, default=0.00)
    clearance_cost = models.DecimalField(_("تكلفة الأرضيات والتخليص"), max_digits=10, decimal_places=2, default=0.00)
    commission_percentage = models.DecimalField(_("نسبة عمولة المورد (%)"), max_digits=5, decimal_places=2, default=5.00)

    notes = models.TextField(blank=True, verbose_name=_("ملاحظات"))

    class Meta:
        verbose_name = _("فاتورة مشتريات")
        verbose_name_plural = _("فواتير المشتريات")
        ordering = ['-invoice_date', '-id']

    def __str__(self):
        return f"[{self.invoice_number}] {self.supplier.name if self.supplier else 'بدون مورد'} - {self.total_amount}"

    def save(self, *args, **kwargs):
        # Auto-generate the internal invoice number (e.g., PINV-00001)
        if not self.invoice_number:
            branch_id = getattr(self, 'branch_id', 1) 
            seq_key = f"pinv_branch_{branch_id}"
            self.invoice_number = Sequence.next_number(seq_key, prefix='PINV-', padding=5)
            
        super().save(*args, **kwargs)