# Generated by Django 6.0.2 on 2026-02-23 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Partner',
        ),
    ]
