# Generated by Django 6.0.2 on 2026-03-01 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='balance',
        ),
    ]
