# Generated by Django 6.0.2 on 2026-03-11 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_payment'),
        ('sales', '0002_salesinvoice_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('credit', 'آجل (على الحساب)'), ('cash', 'كاش (نقدي)')], max_length=10, verbose_name='طريقة الدفع'),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='treasury_account',
            field=models.ForeignKey(blank=True, limit_choices_to={'code__startswith': '1001'}, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='cash_sales', to='accounting.account', verbose_name='حساب الخزينة (للكاش)'),
        ),
    ]
