# Generated by Django 6.0 on 2026-10-03 15:06

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_salesinvoice_cancellation_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, help_text='يُحدّث فقط عبر تخصيص سندات القبض.', max_digits=12, verbose_name='المبلغ المسدد'),
        ),
    ]
